INSERT INTO interestarea (interestAreaIdPk, interestAreaName, InterestAreaProductOrService) VALUES
(1, 'Art classes', 2),
(2, 'Music lessons', 2),
(3, 'Live theatre performances', 2),
(4, 'Concerts', 2),
(5, 'Open mic nights', 2),
(6, 'Guided cultural tours', 2),
(7, 'Museum visits', 2),
(8, 'Gallery visits', 2),
(9, 'Photography services', 2),
(10, 'Videography services', 2),
(11, 'Graphic design', 2),
(12, 'Digital design', 2),
(13, 'Original artwork', 1),
(14, 'Handmade ceramics', 1),
(15, 'Independent books', 1),
(16, 'Local zines and magazines', 1),
(17, 'Limited edition posters', 1),
(18, 'Artisan stationery', 1);